version: 1.0.{build}-{branch}

image: Visual Studio 2017

shallow_clone: false
clone_depth: 5

install:
  - git submodule update --init --recursive
  - ps: >-
      if($isWindows) {
        nuget restore
      }

before_test:
  - ps: Invoke-WebRequest 'https://github.com/kovarex/BhaalBot/raw/master/Starcraft/BROODAT.MPQ' -OutFile 'C:/projects/bwem-community/BrooDat.mpq'
  - cmd: timeout 5 > NUL
  - ps: Invoke-WebRequest 'https://github.com/kovarex/BhaalBot/raw/master/Starcraft/STARDAT.MPQ' -OutFile 'C:/projects/bwem-community/StarDat.mpq.enc'
  - cmd: timeout 5 > NUL
  - ps: Invoke-WebRequest 'https://github.com/kovarex/BhaalBot/raw/master/Starcraft/patch_rt.mpq' -OutFile 'C:/projects/bwem-community/patch_rt.mpq.enc'
  - cmd: move *.mpq %CONFIGURATION%/

build:
  project: BWEM.sln
  parallel: true

platform: x86

configuration:
  - Release
  - Debug

test_script:
  - cmd: pushd %CONFIGURATION%
  - sh: ./tests --gtest_output=xml:"tests.xml"
  - cmd: 'Tests.exe --gtest_output=xml:"tests.xml"'
  - ps: (new-object net.webclient).UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\tests.xml))
